[build-system]
requires = [
    "ffmpeg-python",
    "matplotlib",
    "numpy",
    "pandas",
    "pychord",	
    "scipy",
    "setuptools>=42",
    "sf2utils",
    "tqdm",
    "wavio",
    "wheel"
]
build-backend = "setuptools.build_meta"